- name: "Set up a Vaultwarden server"
  hosts: "{{ target if target is defined else 'vaultwarden_servers' }}"
  become: true

  roles:
    # This role has no tasks at all
    - role: galaxy/com.devture.ansible.role.playbook_help

    # This role has no tasks at all
    - role: galaxy/com.devture.ansible.role.systemd_docker_base

    - role: custom/devture_vaultwarden_playbook_migration

    - when: devture_vaultwarden_playbook_docker_installation_enabled | bool
      role: galaxy/geerlingguy.docker
      vars:
        docker_install_compose: false
      tags:
        - setup-docker
        - setup-all
        - install-docker
        - install-all

    - when: devture_docker_sdk_for_python_installation_enabled | bool
      role: galaxy/com.devture.ansible.role.docker_sdk_for_python
      tags:
        - setup-docker
        - setup-all
        - install-docker
        - install-all

    - when: devture_timesync_installation_enabled | bool
      role: galaxy/com.devture.ansible.role.timesync
      tags:
        - setup-timesync
        - setup-all
        - install-timesync
        - install-all

    - role: custom/devture_vaultwarden_playbook_base

    - role: galaxy/com.devture.ansible.role.postgres

    - role: custom/devture_vaultwarden

    - role: custom/devture_vaultwarden_backup

    - role: galaxy/com.devture.ansible.role.postgres_backup

    - role: galaxy/com.devture.ansible.role.container_socket_proxy

    - role: galaxy/com.devture.ansible.role.traefik

    - when: devture_systemd_service_manager_enabled | bool
      role: galaxy/com.devture.ansible.role.systemd_service_manager

    # This is pretty much last, because we want it to better serve as a "last known good configuration".
    # See: https://github.com/spantaleev/matrix-docker-ansible-deploy/pull/2217#issuecomment-1301487601
    - when: devture_playbook_state_preserver_enabled | bool
      role: galaxy/com.devture.ansible.role.playbook_state_preserver
      tags:
        - setup-all
        - install-all

    - role: galaxy/com.devture.ansible.role.playbook_runtime_messages
