---

- name: (Deprecation) Catch and report renamed Vaultwarden settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'devture_vaultwarden_playbook_traefik_role_enabled', 'new': 'devture_traefik_enabled'}
    - {'old': 'devture_vaultwarden_server_fqn', 'new': 'devture_vaultwarden_hostname'}
